# le agregae nombres a los contenedores
version: '3.8'
#leer comentarios de abajo ->
services:
  mysql:
    image: mysql:latest
    container_name: baseDatos
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./baseDatos:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - networking

  php:
    build: .
    container_name: servidorPHP
    ports:
      - "9090:80"
    volumes:
      - ./ProyectoFinal-IngenieriaII:/var/www/html
    networks:
      - networking
    depends_on:
      - mysql

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
      networks:
      - networking
      depends_on:
      - mysql

networks:
  networking:
    driver: bridge


#cuando se ejecuta el docker compose se creeara una capeta con los nombres de base Datos y ProyectoFinal-IngenieriaII
#en el archivo ProyectoFinal-IngenieriaII deben colocar la carpeta src para que se pueda ejecutar dentro del contenedor 
# contraseña y usuario es root
